export const actors = () => [
  'Denzel Washington',
  'Marilyn Monroe',
  'Robert De Niro',
  'Cate Blanchett',
  'Christian Bale',
  'Penélope Cruz',
  'Kate Winslet',
  'Anthony Hopkins',
  'Meryl Streep',
  'Jack Nicholson',
  'Leonardo DiCaprio',
  'Tom Cruise',
  'Heath Ledger',
  'Tom Hanks',
  'Al Pacino',
  'Morgan Freeman',
  'Nicole Kidman',
  'Timothée Chalamet',
]
